# Configuration for Urban Pulse
api:
  openweathermap_key: "ae46737865d612636d2155263c18bad2"
database:
  path: "urbanpulse.db"
cities:
  - Toronto
  - Vancouver
  - Montreal
logging:
  level: INFO
  file: "urban_pulse.log"
